# Generated by Django 2.1.8 on 2019-10-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_vaild_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('goods_location', models.CharField(max_length=32)),
                ('goods_safe_date', models.IntegerField()),
                ('goods_pro_time', models.DateField(auto_now=True)),
                ('goods_status', models.IntegerField()),
                ('goods_description', models.TextField(default='好吃还不贵，快来抢购！！！')),
                ('picture', models.ImageField(upload_to='images')),
                ('goods_store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.Login_User')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32)),
                ('type_description', models.TextField()),
                ('type_picture', models.ImageField(upload_to='seller/images')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType'),
        ),
    ]
