"""
Django settings for MyShop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#gm4hs63+t^xw-s=($mnm-9-r60@quk+k$k2j*5#fpfot-@6=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery'
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'MyShop.middleware.MiddleWareTest',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'MyShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR,'static'),)

# STATIC_ROOT = os.path.join(BASE_DIR,'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':[
            "127.0.0.1:11211" #本地memcache的地址窗口
        ]
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'




alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu82V9YSgeTnO23LxuYcHdUOByYWdBcJglDCROtMQ52CB4W11iNPZVN7xpiY6G8frAdRuI3lZ1zLEA8t17qZ/RDYIv54uJuhH3lhUlUwbmmSbGl96OdS4EoXFCqDAvCH7xeGTvoixgqYteZjFkTDtPTf8HJPvZfmSFIEnoDjFi6McF7RClMtZQJCOjxdZRb/RP0WPtm+9e1eR43QOTfgYOGq3bVCJ4CRy3m+eLLnoCjbA7gTwQmSsQ8U9PjZlEr5TyhI7bk7wsG239Cmk6FEXJ0igwMBWvXGEBgWsAWsjXrq4XMKD7ZRRCa+o5+fcsrAxZPka0z1aVJeReE45iutunQIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAu82V9YSgeTnO23LxuYcHdUOByYWdBcJglDCROtMQ52CB4W11iNPZVN7xpiY6G8frAdRuI3lZ1zLEA8t17qZ/RDYIv54uJuhH3lhUlUwbmmSbGl96OdS4EoXFCqDAvCH7xeGTvoixgqYteZjFkTDtPTf8HJPvZfmSFIEnoDjFi6McF7RClMtZQJCOjxdZRb/RP0WPtm+9e1eR43QOTfgYOGq3bVCJ4CRy3m+eLLnoCjbA7gTwQmSsQ8U9PjZlEr5TyhI7bk7wsG239Cmk6FEXJ0igwMBWvXGEBgWsAWsjXrq4XMKD7ZRRCa+o5+fcsrAxZPka0z1aVJeReE45iutunQIDAQABAoIBABpjrBPA3C/MoLWTdEYGpFSk9MLVhJf/lUSdgnrKl9B7biS4FdDxO9PCNCCNtJKcx/gM2qEfdzFXD9Ycq+ip+q4iDZ6nYoLTFu42aURFWoeaZXUSP4GK04a+x05UAmEtQUywAuu+F3ttUGyKvBBH2L5GdKWrX/NrW0yITYIlGBUjy6cdki2iL2wZ0xEHcM3i3VQGSnfnxWmWSGwvlyE3ee1YlpGNvfl87yFL/Bd650rulbMpwmHhnaGcsHl4eXG8aujQPguxBuEvFH8vDMm8P5Zffy3FHW8ZZp1GyRS37eCoogCV3heHKGNJZy9m1t8NojofonEIhRT2pBlxOtc0CkECgYEA5nC9Mkg7MrjFvdeQiUbN4btVY2KraszwrQD5LNihNY4DzSnlUMGtR+PCv6EEAmcAMvFI5yKsVqbxQLtD/w1Joq0BGEeRodi/4OrXQAXSvryjnJ/mdDLMj8K+nA2XLX/eoC1rHwbLODsxHopJtotq1Jv0dhK8zmLnxZQFnnaCgy0CgYEA0KItbh1Zt/58laX4rm772pX9gL87Ei2I5FDQPgi2V8JvCOTPgcBJD2Vyl4/vpEJWXeb0iR64J0P5UWCIg9DdOb0Z15+ihZKZlV47dfWQBDlpEP3mVUoZlBZtRp5t8yFB0e5Z568uSYaVmbdS+SZlKBXUkEX+VVyGiojCsM5xfzECgYEAw1WzeqjxzUgFDqxor4TeRkdm1S0xgwGfzfayQUqMNHpiTIoEAVV7TiIJ1ihl3qdy6rvPAWZJ0dYHUMislcmsroGaGPupvhieZciLl5CYGOiMg9qjHcJl1kLNEjkO+hmXHA4D7LP0lYDPXUT5wQwjDX/5VBEEDKqYLsoPjUiFzy0CgYEAxhVkisrFFyNBCBhHrt3is1t7D5UAsbaX5SYxQOSms1YAc/JCbg+xjjOkg+/99/ef5pHUFKgc8fLgsPm1Q2m30Q0Qjx+af7V7qkyIqetXLBuR/LcDzHCJLofIgqcC/zbRNk9V/tndWaO1P/fFiJaCrndjlQNPgZ5Sgw9rwdCQA9ECgYEAznvXFGfiWnx0BTqZ77vrMnxL44KpWFU8Rl7LyFRMsdSmsWNiK9ILwTe+XyGcDQxu7SykcAN5u2fDV5MjWTd9gdilI2V4YRU16xN+AYXGfWuhKGACBthinAEcbV1fGHCXShDzTybTz2T8ucMG2ORTM0KcWfrg1Hik7jz3EZLBPJE=
-----END RSA PRIVATE KEY-----"""

DING_URL = "https://oapi.dingtalk.com/robot/send?access_token=d1e8b271ee11da2a3f4f1a9bf35f1613b422a7af74552c8e510b968d53333474"

import djcelery
djcelery.setup_loader()
BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_IMPORTS = ('CeleryTask.tasks')
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabasesScheduler'

